---
title:       Belajar Bahasa Lorem Ipsum Cara Susah
lang:        id
lang_dir:    ltr
date:        2012-11-1
author:      Akeda Bagus
license:     Creative Commons 3.0 Attribution License
license_url: http://creativecommons.org/licenses/by/3.0/
chapters:
  - Instal_Lorem_Ipsum
  - Memulai_Lorem_Ipsum
  - Tipe_Data_Bawaan_Lorem_Ipsum
  - Variabel
  - Struktur_Kontrol
  - Tipe_Data_Komposit_Lorem_Ipsum
  - Fungsi
  - Class_dan_Object
  - Langkah_Selanjutnya
